
package partuzabook.integracion.ws.contenido;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ContenidoService", targetNamespace = "http://edu.tsi2.ws/integracion/ws/contenido", wsdlLocation = "file:/C:/_Person/fing/TSI2/obligatorio/Partuzabook/IntegracionWebSvc/build/../src/partuzabook/integracion/ws/contenido/ContenidoService.wsdl")
public class ContenidoService
    extends Service
{

    private final static URL CONTENIDOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(partuzabook.integracion.ws.contenido.ContenidoService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = partuzabook.integracion.ws.contenido.ContenidoService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/_Person/fing/TSI2/obligatorio/Partuzabook/IntegracionWebSvc/build/../src/partuzabook/integracion/ws/contenido/ContenidoService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/_Person/fing/TSI2/obligatorio/Partuzabook/IntegracionWebSvc/build/../src/partuzabook/integracion/ws/contenido/ContenidoService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CONTENIDOSERVICE_WSDL_LOCATION = url;
    }

    public ContenidoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContenidoService() {
        super(CONTENIDOSERVICE_WSDL_LOCATION, new QName("http://edu.tsi2.ws/integracion/ws/contenido", "ContenidoService"));
    }

    /**
     * 
     * @return
     *     returns Contenido
     */
    @WebEndpoint(name = "ContenidoPort")
    public Contenido getContenidoPort() {
        return super.getPort(new QName("http://edu.tsi2.ws/integracion/ws/contenido", "ContenidoPort"), Contenido.class);
    }

}
