
package partuzabook.integracion.ws.contenido;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Contenido", targetNamespace = "http://edu.tsi2.ws/integracion/ws/contenido")
public interface Contenido {


    /**
     * 
     * @param total
     * @param eventId
     * @param contenido
     */
    @WebMethod
    @RequestWrapper(localName = "getAlbumContents", targetNamespace = "http://edu.tsi2.ws/integracion/ws/contenido", className = "partuzabook.integracion.ws.contenido.ContentRequest")
    @ResponseWrapper(localName = "getAlbumContentsResponse", targetNamespace = "http://edu.tsi2.ws/integracion/ws/contenido", className = "partuzabook.integracion.ws.contenido.ContentResponse")
    public void getAlbumContents(
        @WebParam(name = "eventId", targetNamespace = "")
        int eventId,
        @WebParam(name = "contenido", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<List<Contenido_Type>> contenido,
        @WebParam(name = "total", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> total);

}
