
package partuzabook.integracion.ws.productora_web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IntegracionWSServicePortType", targetNamespace = "http://ejb.integracion.tsi2.fing.edu.uy")
public interface IntegracionWSServicePortType {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(action = "urn:searchEventByName")
    @WebResult(targetNamespace = "http://ejb.integracion.tsi2.fing.edu.uy")
    @RequestWrapper(localName = "searchEventByName", targetNamespace = "http://ejb.integracion.tsi2.fing.edu.uy", className = "partuzabook.integracion.ws.productora_web.SearchEventByName")
    @ResponseWrapper(localName = "searchEventByNameResponse", targetNamespace = "http://ejb.integracion.tsi2.fing.edu.uy", className = "partuzabook.integracion.ws.productora_web.SearchEventByNameResponse")
    public Object searchEventByName(
        @WebParam(name = "name", targetNamespace = "http://ejb.integracion.tsi2.fing.edu.uy")
        String name);

    /**
     * 
     * @param date
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(action = "urn:searchEventByDate")
    @WebResult(targetNamespace = "http://ejb.integracion.tsi2.fing.edu.uy")
    @RequestWrapper(localName = "searchEventByDate", targetNamespace = "http://ejb.integracion.tsi2.fing.edu.uy", className = "partuzabook.integracion.ws.productora_web.SearchEventByDate")
    @ResponseWrapper(localName = "searchEventByDateResponse", targetNamespace = "http://ejb.integracion.tsi2.fing.edu.uy", className = "partuzabook.integracion.ws.productora_web.SearchEventByDateResponse")
    public Object searchEventByDate(
        @WebParam(name = "date", targetNamespace = "http://ejb.integracion.tsi2.fing.edu.uy")
        XMLGregorianCalendar date);

    /**
     * 
     * @param eventID
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(action = "urn:getAlbumContents")
    @WebResult(targetNamespace = "http://ejb.integracion.tsi2.fing.edu.uy")
    @RequestWrapper(localName = "getAlbumContents", targetNamespace = "http://ejb.integracion.tsi2.fing.edu.uy", className = "partuzabook.integracion.ws.productora_web.GetAlbumContents")
    @ResponseWrapper(localName = "getAlbumContentsResponse", targetNamespace = "http://ejb.integracion.tsi2.fing.edu.uy", className = "partuzabook.integracion.ws.productora_web.GetAlbumContentsResponse")
    public Object getAlbumContents(
        @WebParam(name = "eventID", targetNamespace = "http://ejb.integracion.tsi2.fing.edu.uy")
        String eventID);

    /**
     * 
     * @param type
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(action = "urn:searchEventByType")
    @WebResult(targetNamespace = "http://ejb.integracion.tsi2.fing.edu.uy")
    @RequestWrapper(localName = "searchEventByType", targetNamespace = "http://ejb.integracion.tsi2.fing.edu.uy", className = "partuzabook.integracion.ws.productora_web.SearchEventByType")
    @ResponseWrapper(localName = "searchEventByTypeResponse", targetNamespace = "http://ejb.integracion.tsi2.fing.edu.uy", className = "partuzabook.integracion.ws.productora_web.SearchEventByTypeResponse")
    public Object searchEventByType(
        @WebParam(name = "type", targetNamespace = "http://ejb.integracion.tsi2.fing.edu.uy")
        Integer type);

}
