
package partuzabook.integracion.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Busqueda", targetNamespace = "http://edu.tsi2.ws/integracion/ws/busqueda")
public interface Busqueda {


    /**
     * 
     * @param total
     * @param maxEventos
     * @param nombre
     * @param evento
     */
    @WebMethod
    @RequestWrapper(localName = "searchByName", targetNamespace = "http://edu.tsi2.ws/integracion/ws/busqueda", className = "partuzabook.integracion.ws.SearchRequest")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "http://edu.tsi2.ws/integracion/ws/busqueda", className = "partuzabook.integracion.ws.SearchResponse")
    public void searchByName(
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "maxEventos", targetNamespace = "")
        int maxEventos,
        @WebParam(name = "evento", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<List<Evento>> evento,
        @WebParam(name = "total", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> total);

}
