
package partuzabook.integracion.ws.productora_web;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "IntegracionWSService", targetNamespace = "http://ejb.integracion.tsi2.fing.edu.uy", wsdlLocation = "file:/C:/_Person/fing/TSI2/obligatorio/Partuzabook/IntegracionWebSvc/build/../src/partuzabook/integracion/ws/productora_web/integracionWSService.wsdl")
public class IntegracionWSService
    extends Service
{

    private final static URL INTEGRACIONWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(partuzabook.integracion.ws.productora_web.IntegracionWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = partuzabook.integracion.ws.productora_web.IntegracionWSService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/_Person/fing/TSI2/obligatorio/Partuzabook/IntegracionWebSvc/build/../src/partuzabook/integracion/ws/productora_web/integracionWSService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/_Person/fing/TSI2/obligatorio/Partuzabook/IntegracionWebSvc/build/../src/partuzabook/integracion/ws/productora_web/integracionWSService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INTEGRACIONWSSERVICE_WSDL_LOCATION = url;
    }

    public IntegracionWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntegracionWSService() {
        super(INTEGRACIONWSSERVICE_WSDL_LOCATION, new QName("http://ejb.integracion.tsi2.fing.edu.uy", "IntegracionWSService"));
    }

    /**
     * 
     * @return
     *     returns IntegracionWSServicePortType
     */
    @WebEndpoint(name = "IntegracionWSServiceHttpSoap11Endpoint")
    public IntegracionWSServicePortType getIntegracionWSServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://ejb.integracion.tsi2.fing.edu.uy", "IntegracionWSServiceHttpSoap11Endpoint"), IntegracionWSServicePortType.class);
    }

}
