
package partuzabook.integracion.ws.busqueda;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "BusquedaService", targetNamespace = "http://edu.tsi2.ws/integracion/ws/busqueda", wsdlLocation = "file:/C:/_Person/fing/TSI2/obligatorio/Partuzabook/IntegracionWebSvc/build/../src/partuzabook/integracion/ws/busqueda/BusquedaService.wsdl")
public class BusquedaService
    extends Service
{

    private final static URL BUSQUEDASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(partuzabook.integracion.ws.busqueda.BusquedaService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = partuzabook.integracion.ws.busqueda.BusquedaService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/_Person/fing/TSI2/obligatorio/Partuzabook/IntegracionWebSvc/build/../src/partuzabook/integracion/ws/busqueda/BusquedaService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/_Person/fing/TSI2/obligatorio/Partuzabook/IntegracionWebSvc/build/../src/partuzabook/integracion/ws/busqueda/BusquedaService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BUSQUEDASERVICE_WSDL_LOCATION = url;
    }

    public BusquedaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BusquedaService() {
        super(BUSQUEDASERVICE_WSDL_LOCATION, new QName("http://edu.tsi2.ws/integracion/ws/busqueda", "BusquedaService"));
    }

    /**
     * 
     * @return
     *     returns Busqueda
     */
    @WebEndpoint(name = "BusquedaPort")
    public Busqueda getBusquedaPort() {
        return super.getPort(new QName("http://edu.tsi2.ws/integracion/ws/busqueda", "BusquedaPort"), Busqueda.class);
    }

}
